<?php

namespace P\CarnetBundle\Repository;

/**
 * ContacteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContacteRepository extends \Doctrine\ORM\EntityRepository
{
}
